### ISSUE TITLE
Bot::Builder should use JSON::Builder

### ISSUE THREAD

**Issue by bcardiff** [zmalltalker/crystal-messenger-bot#1]
Hi, I was up to play with messenger bots and I found this shard :-)
I notice that the builder are using plain string interpolations instead of [JSON::Builder](https://crystal-lang.org/api/0.19.2/JSON/Builder.html) and hence, for example, any string with double quotes will break things.

Also, as a starter, I wasn't able to find a http handler or http server that will serve to respond facebook webhook. Any plan on adding them?

**Comment by zmalltalker** [comment]
Gee, JSON::Builder sure seems like the way to go here. I started out using JSON.mapping, but that quickly turned against me. I'll keep this issue open to remind me, or keep my fingers crossed for a PR 😀 

As for HTTP, my current focus is on building outgoing messages and parsing webhook messages, in my current spikes I've just used [Kemal](http://kemalcr.com/) for HTTP. But I'm completely open to suggestions on how to integrate HTTP into this library.
